//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickMagik.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings2012 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings2012 defaultInstance = ((Settings2012)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings2012())));
        
        public static Settings2012 Default {
            get {
                return defaultInstance;
            }
        }
    }
}
